from construct import Enum, Byte, Int32ul, Int32sl

GbxEProdState = Enum(Byte, Aborted=0, GameBox=1, DevBuild=2, Release=3)
GbxEItemType = Enum(
    Int32ul,
    Undefined=0,
    Ornament=1,
    PickUp=2,
    Character=3,
    Vehicle=4,
    Spot=5,
    Cannon=6,
    Group=7,
    Decal=8,
    Turret=9,
    Wagon=10,
    Block=11,
    EntitySpawner=12,
    DeprecV=13,
    Procedural=14,
)
GbxEDefaultCam = Enum(
    Int32ul,
    No=0,
    Default=1,
    Free=2,
    Spectator=3,
    Behind=4,
    Close=5,
    Internal=6,
    Helico=7,
    FirstPerson=8,
    ThirdPerson=9,
    ThirdPersonTop=10,
    Iso=11,
    IsoFocus=12,
    Dia3=13,
    Board=14,
    MonoScreen=15,
    Rear=16,
    Debug=17,
    _1=18,
    _2=19,
    _3=20,
    Alt1=21,
    Orbital=22,
    Decals=23,
    Snap=24,
)
GbxELayerType = Enum(
    Int32ul,
    Geometry=0,
    Smooth=1,
    Translation=2,
    Rotation=3,
    Scale=4,
    Mirror=5,
    U07=6,
    U08=7,
    Subdivide=8,
    Chaos=9,
    U11=10,
    U12=11,
    Deformation=12,
    Cubes=13,
    Trigger=14,
    SpawnPosition=15,
)
GbxEWaypointType = Enum(
    Int32ul, Start=0, Finish=1, Checkpoint=2, No=3, StartFinish=4, Dispenser=5
)
GbxETexAddress = Enum(Int32ul, Wrap=0, Mirror=1, Clamp=2, Border=3)
GbxESurfType = Enum(
    Int32sl,
    Sphere=0,
    Ellipsoid=1,
    Box=6,  # (Primitive)
    Mesh=7,
    VCylinder=8,  # (Primitive)
    MultiSphere=9,  # (Primitive)
    ConvexPolyhedron=10,
    Capsule=11,  # (Primitive)
    Circle=12,  #  (Non3d)
    Compound=13,
    SphereLocated=14,  # (Primitive)
    CompoundInstance=15,
    Cylinder=16,  # (Primitive)
    SphericalShell=17,
)
GbxEPlugSurfacePhysicsId = Enum(
    Byte,
    Concrete=0,
    Pavement=1,
    Grass=2,
    Ice=3,
    Metal=4,
    Sand=5,
    Dirt=6,
    Turbo_Deprecated=7,
    DirtRoad=8,
    Rubber=9,
    SlidingRubber=10,
    Test=11,
    Rock=12,
    Water=13,
    Wood=14,
    Danger=15,
    Asphalt=16,
    WetDirtRoad=17,
    WetAsphalt=18,
    WetPavement=19,
    WetGrass=20,
    Snow=21,
    ResonantMetal=22,
    GolfBall=23,
    GolfWall=24,
    GolfGround=25,
    Turbo2_Deprecated=26,
    Bumper_Deprecated=27,
    NotCollidable=28,
    FreeWheeling_Deprecated=29,
    TurboRoulette_Deprecated=30,
    WallJump=31,
    MetalTrans=32,
    Stone=33,
    Player=34,
    Trunk=35,
    TechLaser=36,
    SlidingWood=37,
    PlayerOnly=38,
    Tech=39,
    TechArmor=40,
    TechSafe=41,
    OffZone=42,
    Bullet=43,
    TechHook=44,
    TechGround=45,
    TechWall=46,
    TechArrow=47,
    TechHook2=48,
    Forest=49,
    Wheat=50,
    TechTarget=51,
    PavementStair=52,
    TechTeleport=53,
    Energy=54,
    TechMagnetic=55,
    TurboTechMagnetic_Deprecated=56,
    Turbo2TechMagnetic_Deprecated=57,
    TurboWood_Deprecated=58,
    Turbo2Wood_Deprecated=59,
    FreeWheelingTechMagnetic_Deprecated=60,
    FreeWheelingWood_Deprecated=61,
    TechSuperMagnetic=62,
    TechNucleus=63,
    TechMagneticAccel=64,
    MetalFence=65,
    TechGravityChange=66,
    TechGravityReset=67,
    RubberBand=68,
    Gravel=69,
    Hack_NoGrip_Deprecated=70,
    Bumper2_Deprecated=71,
    NoSteering_Deprecated=72,
    NoBrakes_Deprecated=73,
    RoadIce=74,
    RoadSynthetic=75,
    Green=76,
    Plastic=77,
    DevDebug=78,
    Free3=79,
    XXX_Null=80,
)

GbxEPlugSurfaceGameplayId = Enum(
    Byte,
    No=0,
    Turbo=1,
    Turbo2=2,
    TurboRoulette=3,
    FreeWheeling=4,
    NoGrip=5,
    NoSteering=6,
    ForceAcceleration=7,
    Reset=8,
    SlowMotion=9,
    Bumper=10,
    Bumper2=11,
    ReactorBoost_Legacy=12,
    Fragile=13,
    ReactorBoost2_Legacy=14,
    Bouncy=15,
    NoBrakes=16,
    Cruise=17,
    ReactorBoost_Oriented=18,
    ReactorBoost2_Oriented=19,
    XXX_Null=20,
)
GbxEFillDir = Enum(Int32ul, U=0, V=1)
GbxEFillAlign = Enum(Int32ul, Center=0, Begin=1, End=2)
